version: 2.1
orbs:
  python: circleci/python@1.2
jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run unit tests
          command: pytest test/unit
      - run:
          name: Run integration tests
          command: pytest test/integration
workflows:
  sample:
    jobs:
      - build-and-test
